version: "3"

services:
  skyros.mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: "skyros.mysql.database"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - default
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  skyros.userservice:
    image: skyros-user-service:latest
    container_name: skyros.userservice.svc
    command: /app/skyros-user-service
    ports:
      - '4001:4001'
    restart: always
    environment:
      - MYSQL_HOST=skyros.mysql.database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DBNAME=userservice
      - SECRET_KEY=userservice-secret-key
      - SERVER_ADDRESS=:4001
      - GRPC_SERVER_ADDRESS=4011
    depends_on:
      - skyros.mysql
    networks:
      - default
