# Start by building the application.
FROM golang:1.18-alpine3.16 as build

ARG GITHUB_TOKEN

RUN apk add --no-cache git

RUN git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"

WORKDIR /skyros-order-service

COPY orderservice .

RUN export GOSUMDB=off

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o skyros-order-service github.com/situmorangbastian/skyros/orderservice/cmd/orderservice

FROM gcr.io/distroless/static

WORKDIR /skyros-order-service

COPY --from=build /skyros-order-service /app

EXPOSE 4002

CMD ["/app/skyros-order-service"]
