FROM golang:1.19-alpine3.18 as build

WORKDIR /skyros-reverseproxy-service

COPY reverseproxyservice .

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o skyros-reverseproxy-service github.com/situmorangbastian/skyros/reverseproxyservice

FROM gcr.io/distroless/static

WORKDIR /skyros-reverseproxy-service

COPY --from=build /skyros-reverseproxy-service /app

COPY --from=build /skyros-reverseproxy-service/config.toml .

EXPOSE 4000

CMD ["/app/skyros-reverseproxy-service"]
