FROM golang:1.21.2-alpine3.18 as build

WORKDIR /skyros-product-service

COPY productservice .

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o skyros-product-service github.com/situmorangbastian/skyros/productservice/cmd/productservice

FROM gcr.io/distroless/static

WORKDIR /skyros-product-service

COPY --from=build /skyros-product-service /app

EXPOSE 4002

CMD ["/app/skyros-product-service"]
