FROM golang:1.19-alpine3.18 as build

WORKDIR /skyros-order-service

COPY orderservice .

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o skyros-order-service github.com/situmorangbastian/skyros/orderservice/cmd/orderservice

FROM gcr.io/distroless/static

WORKDIR /skyros-order-service

COPY --from=build /skyros-order-service /app

EXPOSE 4002

CMD ["/app/skyros-order-service"]
