version: "3"

services:
  skyros.mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: "skyros.mysql.database"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - default
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  skyros.gatewayservice:
    image: skyros-gateway-service:latest
    container_name: skyros.gatewayservice.svc
    command: /app/skyros-gateway-service
    ports:
      - "4000:4000"
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile-gatewayservice

  skyros.userservice:
    image: skyros-user-service:latest
    container_name: skyros.userservice.svc
    command: /app/skyros-user-service
    ports:
      - "4001:4001"
    restart: always
    environment:
      - DATABASE_URL=root:my-secret-pw@tcp(skyros.mysql.database:3306)/userservice?charset=utf8mb4
      - SECRET_KEY=userservice-secret-key
      - GRPC_SERVER_PORT=4011
      - GRPC_SERVICE_ENDPOINT=skyros.userservice.svc:4011
      - GRPC_GATEWAY_SERVER_PORT=4001
    depends_on:
      - skyros.mysql
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile-userservice

  skyros.productservice:
    image: skyros-product-service:latest
    container_name: skyros.productservice.svc
    command: /app/skyros-product-service
    ports:
      - "4002:4002"
    restart: always
    environment:
      - MYSQL_HOST=skyros.mysql.database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DBNAME=productservice
      - SECRET_KEY=userservice-secret-key
      - SERVER_ADDRESS=:4002
      - GRPC_SERVER_ADDRESS=4012
      - USER_SERVICE_GRPC=skyros.userservice.svc:4011
    depends_on:
      - skyros.mysql
      - skyros.userservice
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile-productservice

  skyros.orderservice:
    image: skyros-order-service:latest
    container_name: skyros.orderservice.svc
    command: /app/skyros-order-service
    ports:
      - "4003:4003"
    restart: always
    environment:
      - MYSQL_HOST=skyros.mysql.database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DBNAME=orderservice
      - SECRET_KEY=userservice-secret-key
      - SERVER_ADDRESS=:4003
      - USER_SERVICE_GRPC=skyros.userservice.svc:4011
      - PRODUCT_SERVICE_GRPC=skyros.productservice.svc:4012
    depends_on:
      - skyros.mysql
      - skyros.userservice
      - skyros.productservice
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile-orderservice
