FROM golang:1.24.2-alpine AS build

WORKDIR /skyros-user-service

COPY ./userservice ./userservice

COPY ./skyrosgrpc ./skyrosgrpc

COPY go.mod go.sum ./

RUN go mod tidy

RUN CGO_ENABLED=0 go build -o skyros-user-service github.com/situmorangbastian/skyros/userservice

FROM gcr.io/distroless/static

WORKDIR /skyros-user-service

COPY --from=build /skyros-user-service /app

EXPOSE 4001

CMD ["/app/skyros-user-service"]
