FROM golang:1.23.1-alpine3.20 AS build

WORKDIR /skyros-product-service

COPY productservice .

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o skyros-product-service github.com/situmorangbastian/skyros/productservice/cmd

FROM gcr.io/distroless/static

WORKDIR /skyros-product-service

COPY --from=build /skyros-product-service /app

EXPOSE 4002

CMD ["/app/skyros-product-service"]
