[server]
address = ":4000"

[[endpoint]]
path = "login"
service = "http://skyros.userservice.svc:4001"

[[endpoint]]
path = "register/buyer"
service = "http://skyros.userservice.svc:4001"

[[endpoint]]
path = "register/seller"
service = "http://skyros.userservice.svc:4001"

[[endpoint]]
path = "order"
service = "http://skyros.orderservice.svc:4003"

[[endpoint]]
path = "product"
service = "http://skyros.productservice.svc:4002"
