[server]
address = ":4000"

[[endpoint]]
path = "v1/users/login"
service = "http://skyros.userservice.svc:4001"

[[endpoint]]
path = "v1/users/register/buyer"
service = "http://skyros.userservice.svc:4001"

[[endpoint]]
path = "v1/users/register/seller"
service = "http://skyros.userservice.svc:4001"

[[endpoint]]
path = "order"
service = "http://skyros.orderservice.svc:4003"

[[endpoint]]
path = "product"
service = "http://skyros.productservice.svc:4002"
