// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	skyros "github.com/situmorangbastian/skyros"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, filter
func (_m *OrderService) Fetch(ctx context.Context, filter skyros.Filter) ([]skyros.Order, string, error) {
	ret := _m.Called(ctx, filter)

	var r0 []skyros.Order
	if rf, ok := ret.Get(0).(func(context.Context, skyros.Filter) []skyros.Order); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]skyros.Order)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, skyros.Filter) string); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, skyros.Filter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: ctx, ID
func (_m *OrderService) Get(ctx context.Context, ID string) (skyros.Order, error) {
	ret := _m.Called(ctx, ID)

	var r0 skyros.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) skyros.Order); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(skyros.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchStatus provides a mock function with given fields: ctx, ID, status
func (_m *OrderService) PatchStatus(ctx context.Context, ID string, status int) error {
	ret := _m.Called(ctx, ID, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, ID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: ctx, order
func (_m *OrderService) Store(ctx context.Context, order skyros.Order) (skyros.Order, error) {
	ret := _m.Called(ctx, order)

	var r0 skyros.Order
	if rf, ok := ret.Get(0).(func(context.Context, skyros.Order) skyros.Order); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(skyros.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, skyros.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
