name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: skyros
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    env:
      TEST_MYSQL_HOST: 127.0.0.1
      TEST_MYSQL_PORT: 3306
      TEST_MYSQL_DBNAME: skyros
      TEST_MYSQL_USER: root
      TEST_MYSQL_PASS: root
    steps:
    - name: Set up Action
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.TEST_MYSQL_DBNAME }};' -u${{ env.TEST_MYSQL_USER }} -p${{ env.TEST_MYSQL_PASS }}

    - name: Run Test
      run: make test
